[profile.default]
src = "src"
test = "test"
script = "script"
libs = ["lib"]
solc_version = "0.8.28"
evm_version = "cancun"
optimizer = true
optimizer_runs = 10_000
remappings = ["forge-std/=lib/forge-std/src/"]

[fmt]
line_length = 120
